name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ignore-main-{0}', github.run_id) || format('{0}-{1}', github.workflow, github.ref_name) }}
  cancel-in-progress: true

jobs:
  lint-report:
    uses: canonical/identity-credentials-workflows/.github/workflows/lint-report.yaml@v0

  static-analysis:
    name: Static analysis
    uses: canonical/identity-credentials-workflows/.github/workflows/static-analysis.yaml@v0

  unit-tests-with-coverage:
    uses: canonical/identity-credentials-workflows/.github/workflows/unit-test.yaml@v0

  build:
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup LXD
        uses: canonical/setup-lxd@main
        with:
            channel: 5.21/stable
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      - name: Build charm under test
        run: charmcraft pack --verbose
      - name: Archive Charm Under Test
        uses: actions/upload-artifact@v4
        with:
          name: built-charm-${{ matrix.arch.arch }}
          path: "*.charm"
          retention-days: 5

  integration-test:
    needs:
      - build
    uses: ./.github/workflows/integration-test.yaml

  publish-charm:
    needs:
      - lint-report
      - static-analysis
      - unit-tests-with-coverage
      - integration-test
    if: ${{ github.ref_name == 'main' || startsWith(github.ref_name, 'release-') }}
    uses: canonical/identity-credentials-workflows/.github/workflows/publish-charm-multiarch.yaml@v0
    secrets:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}
    with:
      track-name: 4
